### ISSUE TITLE
Anyway to make the command prompt file hidden?

### ISSUE THREAD

**Issue by SamGamerYT** [mhils/yeti-volume-sync#3]

**Comment by mhils** [comment]
See README - you can pass `--hide`.

**Comment by SamGamerYT** [comment]
Hmmm I'm using `--hide` within the shortcut's property but it's not.. really hidden, I still see the command prompt.

**Comment by SamGamerYT** [comment]
![image](https://github.com/mhils/yeti-volume-sync/assets/37612109/1dab7ba2-42ca-4c4a-b9c3-606e344c16cd)
